function [Timestamp,PremadeVoltage,ActualSentVoltage,PremadeVelocity,ActualVelocity] = import_initial(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIMESTAMP,PREMADEVOLTAGE,ACTUALSENTVOLTAGE,PREMADEVELOCITY,ACTUALVELOCITY]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIMESTAMP,PREMADEVOLTAGE,ACTUALSENTVOLTAGE,PREMADEVELOCITY,ACTUALVELOCITY]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Timestamp,PremadeVoltage,ActualSentVoltage,PremadeVelocity,ActualVelocity] = importfile('Initial_Recording_Data 08-12-2019 10.01.28.txt',2, 6760);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/08/12 10:18:12

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Timestamp = dataArray{:, 1};
PremadeVoltage = dataArray{:, 2};
ActualSentVoltage = dataArray{:, 3};
PremadeVelocity = dataArray{:, 4};
ActualVelocity = dataArray{:, 5};


