function [WorldTimestamp,RecordingTimestamp,SteamVRGameObjectRoll,SteamVRGameObjectPitch,SteamVRGameObjectYaw,SentTrajectoryYaw] = import_SteamVR_Gameobject(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [WORLDTIMESTAMP,RECORDINGTIMESTAMP,STEAMVRGAMEOBJECTROLL,STEAMVRGAMEOBJECTPITCH,STEAMVRGAMEOBJECTYAW,SENTTRAJECTORYYAW]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [WORLDTIMESTAMP,RECORDINGTIMESTAMP,STEAMVRGAMEOBJECTROLL,STEAMVRGAMEOBJECTPITCH,STEAMVRGAMEOBJECTYAW,SENTTRAJECTORYYAW]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [WorldTimestamp,RecordingTimestamp,SteamVRGameObjectRoll,SteamVRGameObjectPitch,SteamVRGameObjectYaw,SentTrajectoryYaw] = importfile('testOne_SteamVR_Object______Optitrack_Tracking03-02-2020 09.09.59.txt',2, 7229);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/03/02 13:30:56

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
WorldTimestamp = dataArray{:, 1};
RecordingTimestamp = dataArray{:, 2};
SteamVRGameObjectRoll = dataArray{:, 3};
SteamVRGameObjectPitch = dataArray{:, 4};
SteamVRGameObjectYaw = dataArray{:, 5};
SentTrajectoryYaw = dataArray{:, 6};


