function [world_timestamp,world_index,eye_id,confidence,norm_pos_x,norm_pos_y,diameter,method,ellipse_center_x,ellipse_center_y,ellipse_axis_a,ellipse_axis_b,ellipse_angle,diameter_3d,model_confidence,model_id,sphere_center_x,sphere_center_y,sphere_center_z,sphere_radius,circle_3d_center_x,circle_3d_center_y,circle_3d_center_z,circle_3d_normal_x,circle_3d_normal_y,circle_3d_normal_z,circle_3d_radius,theta,phi,projected_sphere_center_x,projected_sphere_center_y,projected_sphere_axis_a,projected_sphere_axis_b,projected_sphere_angle] = import_All_Gaze_Data(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [WORLD_TIMESTAMP,WORLD_INDEX,EYE_ID,CONFIDENCE,NORM_POS_X,NORM_POS_Y,DIAMETER,METHOD,ELLIPSE_CENTER_X,ELLIPSE_CENTER_Y,ELLIPSE_AXIS_A,ELLIPSE_AXIS_B,ELLIPSE_ANGLE,DIAMETER_3D,MODEL_CONFIDENCE,MODEL_ID,SPHERE_CENTER_X,SPHERE_CENTER_Y,SPHERE_CENTER_Z,SPHERE_RADIUS,CIRCLE_3D_CENTER_X,CIRCLE_3D_CENTER_Y,CIRCLE_3D_CENTER_Z,CIRCLE_3D_NORMAL_X,CIRCLE_3D_NORMAL_Y,CIRCLE_3D_NORMAL_Z,CIRCLE_3D_RADIUS,THETA,PHI,PROJECTED_SPHERE_CENTER_X,PROJECTED_SPHERE_CENTER_Y,PROJECTED_SPHERE_AXIS_A,PROJECTED_SPHERE_AXIS_B,PROJECTED_SPHERE_ANGLE]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [WORLD_TIMESTAMP,WORLD_INDEX,EYE_ID,CONFIDENCE,NORM_POS_X,NORM_POS_Y,DIAMETER,METHOD,ELLIPSE_CENTER_X,ELLIPSE_CENTER_Y,ELLIPSE_AXIS_A,ELLIPSE_AXIS_B,ELLIPSE_ANGLE,DIAMETER_3D,MODEL_CONFIDENCE,MODEL_ID,SPHERE_CENTER_X,SPHERE_CENTER_Y,SPHERE_CENTER_Z,SPHERE_RADIUS,CIRCLE_3D_CENTER_X,CIRCLE_3D_CENTER_Y,CIRCLE_3D_CENTER_Z,CIRCLE_3D_NORMAL_X,CIRCLE_3D_NORMAL_Y,CIRCLE_3D_NORMAL_Z,CIRCLE_3D_RADIUS,THETA,PHI,PROJECTED_SPHERE_CENTER_X,PROJECTED_SPHERE_CENTER_Y,PROJECTED_SPHERE_AXIS_A,PROJECTED_SPHERE_AXIS_B,PROJECTED_SPHERE_ANGLE]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [world_timestamp,world_index,eye_id,confidence,norm_pos_x,norm_pos_y,diameter,method,ellipse_center_x,ellipse_center_y,ellipse_axis_a,ellipse_axis_b,ellipse_angle,diameter_3d,model_confidence,model_id,sphere_center_x,sphere_center_y,sphere_center_z,sphere_radius,circle_3d_center_x,circle_3d_center_y,circle_3d_center_z,circle_3d_normal_x,circle_3d_normal_y,circle_3d_normal_z,circle_3d_radius,theta,phi,projected_sphere_center_x,projected_sphere_center_y,projected_sphere_axis_a,projected_sphere_axis_b,projected_sphere_angle] = importfile('pupil_positions.csv',2, 47564);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/03/19 11:49:21

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
world_timestamp = cell2mat(raw(:, 1));
world_index = cell2mat(raw(:, 2));
eye_id = cell2mat(raw(:, 3));
confidence = cell2mat(raw(:, 4));
norm_pos_x = cell2mat(raw(:, 5));
norm_pos_y = cell2mat(raw(:, 6));
diameter = cell2mat(raw(:, 7));
method = cell2mat(raw(:, 8));
ellipse_center_x = cell2mat(raw(:, 9));
ellipse_center_y = cell2mat(raw(:, 10));
ellipse_axis_a = cell2mat(raw(:, 11));
ellipse_axis_b = cell2mat(raw(:, 12));
ellipse_angle = cell2mat(raw(:, 13));
diameter_3d = cell2mat(raw(:, 14));
model_confidence = cell2mat(raw(:, 15));
model_id = cell2mat(raw(:, 16));
sphere_center_x = cell2mat(raw(:, 17));
sphere_center_y = cell2mat(raw(:, 18));
sphere_center_z = cell2mat(raw(:, 19));
sphere_radius = cell2mat(raw(:, 20));
circle_3d_center_x = cell2mat(raw(:, 21));
circle_3d_center_y = cell2mat(raw(:, 22));
circle_3d_center_z = cell2mat(raw(:, 23));
circle_3d_normal_x = cell2mat(raw(:, 24));
circle_3d_normal_y = cell2mat(raw(:, 25));
circle_3d_normal_z = cell2mat(raw(:, 26));
circle_3d_radius = cell2mat(raw(:, 27));
theta = cell2mat(raw(:, 28));
phi = cell2mat(raw(:, 29));
projected_sphere_center_x = cell2mat(raw(:, 30));
projected_sphere_center_y = cell2mat(raw(:, 31));
projected_sphere_axis_a = cell2mat(raw(:, 32));
projected_sphere_axis_b = cell2mat(raw(:, 33));
projected_sphere_angle = cell2mat(raw(:, 34));


