function info1 = import_pupil_time(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   INFO1 = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   INFO1 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   info1 = importfile('info.csv', 4, 4);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/06/06 11:28:59

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 4;
    endRow = 4;
end

%% Format for each line of text:
%   column2: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    dataArray{1} = [dataArray{1};dataArrayBlock{1}];
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
info1 = [dataArray{1:end-1}];

